# Generated by Django 5.2.13 on 2026-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params_app', '0006_vehicle_user_space_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parkingdetectionevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Digital Wallet', 'Digital Wallet'), ('MTN MoMo', 'MTN MoMo'), ('PayPal', 'PayPal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notif_type',
            field=models.CharField(choices=[('space_available', 'Space Available'), ('nearly_full', 'Nearly Full'), ('expiry_warning', 'Expiry Warning'), ('session_ended', 'Session Ended'), ('booking', 'Booking Confirmed'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
