"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure--2=%yzl50=$hgzm=c-&4pep!6%qkaz1637@th5q@35+&u=9mpb")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default="parms2.onrender.com,params-v2.onrender.com,127.0.0.1,localhost", cast=Csv())



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "params_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  


]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Import dj_database_url at the top to avoid issues
import dj_database_url

# Force set DATABASE_URL if we're on Render and it's not set
if ('RENDER' in os.environ or 'RENDER_SERVICE_ID' in os.environ) and not os.environ.get('DATABASE_URL'):
    os.environ['DATABASE_URL'] = 'postgresql://parms2_db_user:spxgiscw2X69gXax4Wa1KksHutEUNiKi@dpg-d4gtodpr0fns739slra0-a.postgres.render.com:5432/parms2_db?sslmode=require'
    print("Manually set DATABASE_URL for Render deployment")

# Check if DATABASE_URL is provided (common in production environments like Render)
DATABASE_URL = config('DATABASE_URL', default=None) or os.environ.get('DATABASE_URL')

# Always print DATABASE_URL status for debugging deployment issues
print(f"DEBUG mode: {DEBUG}")
print(f"DATABASE_URL present: {DATABASE_URL is not None}")
print(f"All environment variables containing 'DATABASE': {[k for k in os.environ.keys() if 'DATABASE' in k.upper()]}")
if DATABASE_URL:
    print(f"DATABASE_URL starts with: {DATABASE_URL[:20]}...")
    print(f"DATABASE_URL contains render.com: {'render.com' in DATABASE_URL}")
else:
    print("No DATABASE_URL found, using local configuration")

# Detect if we're running on Render
IS_RENDER = 'RENDER' in os.environ or 'RENDER_SERVICE_ID' in os.environ
print(f"Running on Render: {IS_RENDER}")

if DATABASE_URL:
    # Parse DATABASE_URL for production (Render provides this)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, conn_health_checks=True)
    }
    print("Using DATABASE_URL configuration")
    print(f"Database host: {DATABASES['default'].get('HOST', 'Unknown')}")
    print(f"Database name: {DATABASES['default'].get('NAME', 'Unknown')}")
elif IS_RENDER:
    # Fallback for Render if DATABASE_URL is somehow not set
    print("WARNING: Running on Render but DATABASE_URL not found! Using hardcoded database.")
    DATABASES = {
        'default': dj_database_url.parse(
            'postgresql://parms2_db_user:spxgiscw2X69gXax4Wa1KksHutEUNiKi@dpg-d4gtodpr0fns739slra0-a.postgres.render.com:5432/parms2_db?sslmode=require',
            conn_max_age=600,
            conn_health_checks=True
        )
    }
elif config('USE_SQLITE_FOR_TESTING', default=False, cast=bool):
    # Temporary SQLite for local development when PostgreSQL isn't available
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    print("Using SQLite configuration")
else:
    # Local development PostgreSQL configuration
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config('DB_NAME', default='parking_db'),
            "USER": config('DB_USER', default='postgres'),
            "PASSWORD": config('DB_PASSWORD', default=''),
            "HOST": config('DB_HOST', default='localhost'),
            "PORT": config('DB_PORT', default='5432'),
        }
    }
    print("Using local PostgreSQL configuration")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# For a global static directory
STATICFILES_DIRS = [BASE_DIR / "static"]

# Specify where static files are collected for deployment
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default authentication
)

LOGIN_URL = '/login'  # Redirect unauthenticated users to the login page
